name: musa-550-fall-2023
channels:
- conda-forge

dependencies:
- altair=5.1.0
- beautifulsoup4=4.12.2
- black=23.7.0
- bokeh=3.2.1
- cartopy=0.21.1
- cenpy=1.0.1
- contextily=1.3.0
- dask=2023.8.0
- datashader=0.15.1
- descartes=1.1.0
- earthpy=0.9.4
- fastparquet=2023.7.0
- flask=2.3.2
- geopandas=0.13.2
- geoviews=1.10.1
- holoviews=1.17.0
- hvplot=0.9.0
- imageio=2.31.1
- intake=0.6.6
- intake-parquet=0.2.3
- intake-xarray=0.7.0
- ipython=8.14.0
- jupyterlab=3.6.5
- jupyterlab_code_formatter=2.2.1
- kneed=0.8.3
- mapclassify=2.5.0
- matplotlib=3.7.2
- missingno=0.4.2
- nbconvert=7.7.3
- networkx=3.1
- nltk=3.8.1
- nodejs=18.16.1
- notebook=6.5.4
- numpy=1.24.4
- openpyxl=3.1.2
- osmnet=0.1.7
- osmnx=1.6.0
- pandana=0.7
- pandas=1.5.3
- panel=1.2.1
- param=1.13.0
- pip=23.2.1
- pyarrow=12.0.1
- pyepsg=0.4.0
- python=3.10.12
- python-snappy=0.6.1
- pytorch::pytorch=2.0.0
- rasterio=1.3.8
- rasterstats=0.19.0
- requests=2.31.0
- rio-toa=0.3.0
- rioxarray=0.14.1
- s3fs=2023.6.0
- scikit-learn=1.3.0
- seaborn=0.12.2
- selenium=4.13.0
- selenium-manager=4.13.0
- shapely=2.0.1
- textblob=0.15.3
- tqdm=4.65.0
- transformers=4.31.0
- vega=4.0.0
- vega_datasets=0.9.0
- vegafusion=1.4.0
- vegafusion-python-embed=1.4.0
- xarray=2023.7.0
- pip:
  - jupyterlab-quarto==0.1.45
  - jupyter-panel-proxy==0.1.0
  - jupyter-server-proxy==4.0.0
  - nbgitpuller==1.2.0
  - pygris==0.1.6
  - pyprojroot==0.3.0
  - us==3.1.1
  - wordcloud==1.9.2